In [1]:
# Import the random module.
import random

In [2]:
random.randint(-90, 90)

-57

In [3]:
random.randrange(-90,89)

33

In [4]:
random.uniform(-90, 90)

-33.28517769888528

In [5]:
random.random()

0.7395925193949204

In [6]:
x = 1
latitudes = []
while x < 11:
    random_lat = random.randint(-90, 89) + random.random()
    latitudes.append(random_lat)
    x += 1

In [7]:
random.randrange(-90, 90, step=1)

7

In [8]:
random.randrange(-90, 90, step=3)

-48

In [9]:
random.uniform(-90, 90)

-57.57217062170929

In [10]:
# Import the NumPy module.
import numpy as np

In [11]:
np.random.uniform(-90.000, 90.000)

-7.925918168707128

In [12]:
np.random.uniform(-90.000, 90.000, size=50)

array([-63.15703222,  62.86457128, -69.7083286 ,  68.24642059,
       -39.28900695, -76.90072483, -33.70098403, -65.16321457,
        67.75408669,   8.85750085,  22.42742683, -64.8585636 ,
        33.5207354 ,  -8.27256336, -79.57442533,  16.82246109,
        89.01519407, -23.54772583, -14.49628575, -55.21119495,
         8.9605642 , -25.63998575, -53.20754659, -58.07908266,
        51.99191794,  53.7824626 ,  44.11410499, -16.14636442,
        67.20786059, -71.02717899, -58.48640661,  -4.73275576,
        -2.47914098,  28.14326333,   8.98400318, -50.35125974,
        26.94396329,  79.63914624, -30.27726288,  51.06468349,
        28.34530017,  78.16728993,  52.79394751,  -5.65236233,
       -51.27832674,  52.5315362 ,  14.70579032,  40.33843853,
        59.73057378,  -7.85648674])

In [13]:
np.random.uniform(low=-90, high=90, size = 50)

array([ -8.07480995, -17.68772761,  84.8571544 , -13.65290824,
       -86.18791214, -40.44203686,  64.80341996,  -2.41449563,
       -55.29772143,  55.44831195, -53.45687062,  86.61192263,
        46.06661004, -46.58062497, -72.40272187,   5.91145464,
        55.37899997,  78.05040359,  -6.57189755,  51.22667682,
        11.33061341, -18.43689741,  81.38866399, -16.3431495 ,
       -40.48758659, -82.92213609,  40.79163947, -72.49562181,
        12.73012164, -24.45015725,   5.1741575 ,  29.78422587,
       -52.73555798,  36.26676345,  -1.1606021 , -70.38736281,
       -17.66575229,  72.25909317,  27.67345683,  43.28812075,
       -41.26179935, -59.2954202 ,  -6.51486204,  65.52814273,
        41.87521554, -31.72109344,  44.26312242, -54.05273382,
       -66.6913053 ,  18.05106411])

In [14]:
# Import timeit.
import timeit

In [15]:
%timeit np.random.uniform(-90.000, 90.000, size=1500)

15.9 µs ± 544 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [16]:
def latitudes(size):
    latitudes = []
    x = 0
    while x < (size):
        random_lat = random.randint(-90, 90) + random.random()
        latitudes.append(random_lat)
        x += 1
    return latitudes
# Call the function with 1500.
%timeit latitudes(1500)

1.46 ms ± 35.3 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [17]:
np.random.uniform(-90.000, 90.000, size=1500)

array([88.89589539, 89.44834867, 19.16762179, ..., 23.49168438,
       29.15997401, -8.18822727])

In [21]:
# Import linear regression from the SciPy stats module.
from scipy.stats import linregress

In [22]:
# Perform linear regression.
(slope, intercept, r_value, p_value, std_err) = linregress(lats, temps)
# Get the equation of the line.
line_eq = "y = " + str(round(slope,2)) + "x + " + str(round(intercept,2))
print(line_eq)
print(f"The p-value is: {p_value:.3f}")

NameError: name 'lats' is not defined

In [23]:
# Calculate the regression line "y values" from the slope and intercept.
regress_values = [(lat * slope + intercept) for lat in lats]

NameError: name 'lats' is not defined