In [1]:
# Import the random module.
import random

In [2]:
random.randint(-90, 90)

-33

In [3]:
random.randrange(-90,89)

65

In [4]:
random.uniform(-90, 90)

-78.29951637970225

In [5]:
random.random()

0.846328691770399

In [6]:
x = 1
latitudes = []

In [7]:
while x < 11:
    random_lat = random.randint(-90, 89) + random.random()
    latitudes.append(random_lat)
    x += 1

In [8]:
random.randrange(-90, 90, step=1)

-26

In [9]:
random.randrange(-90, 90, step=3)

-60

In [10]:
random.uniform(-90, 90)

45.89117914113362

In [11]:
# Import the NumPy module.
import numpy as np

In [12]:
np.random.uniform(-90.000, 90.000)

3.444747720028488

In [13]:
np.random.uniform(-90.000, 90.000, size=50)

array([  2.40855889, -30.80618259, -66.25345421, -32.33633633,
       -22.91301041, -47.04167412, -76.04943793,   9.11694286,
        -4.24505008, -70.52236087, -31.22570845, -62.93606439,
       -19.45640127, -48.55885454,  75.43991737, -67.16356923,
        46.36589843,  30.64587512, -54.1993366 ,  52.94913741,
        22.78613647, -52.5198869 ,   7.66933217, -39.88777231,
        24.76571761,  37.97706764,  54.85457113,  39.91850653,
        66.32123228, -36.53185626,  29.40658486, -54.51293207,
       -23.3609149 , -49.29857173,  72.17007586,  73.1966574 ,
        32.5877346 , -81.84432177,  56.17977522,  84.09350145,
       -58.91304456, -31.70079528, -38.13124742,  73.74604161,
        31.86279354, -44.65807518,   4.33699774, -62.00432501,
       -87.59345018, -54.35340211])

In [18]:
np.random.uniform(low=-90, high=90, size = 50)

array([-51.88173372, -73.27811893,  41.38937866, -88.4233676 ,
       -81.44337563,  24.21275763,  71.76333558, -20.62864516,
        57.2959382 ,  27.27455035,  -2.27342091, -81.2829748 ,
       -64.63215427, -70.16976104,  40.85758872,  67.14109969,
        15.54558398,  -6.92340948, -34.53021439,  47.54155855,
         6.5439732 ,  64.38116918, -31.14030562,   7.93365348,
        -4.72710142,  21.27461071, -74.90057693,  29.14331061,
        -7.898256  ,  14.73085213, -34.34273067, -59.26696632,
       -54.10942262,  -0.96558233,  64.44138755,  22.2136079 ,
       -20.05428043, -72.9812252 ,  83.07246229,   4.09659856,
        77.93894894,   5.94465458,  11.33328356, -29.49836749,
       -67.98283781,   8.59968394, -54.29182225,  59.66026361,
        48.80227889,  10.16265034])

In [14]:
# Import timeit.
import timeit

In [15]:
%timeit np.random.uniform(-90.000, 90.000, size=1500)

23.8 µs ± 8.99 µs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [16]:
def latitudes(size):
    latitudes = []
    x = 0
    while x < (size):
        random_lat = random.randint(-90, 90) + random.random()
        latitudes.append(random_lat)
        x += 1
    return latitudes
# Call the function with 1500.
%timeit latitudes(1500)

2.94 ms ± 75.4 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [19]:
np.random.uniform(-90.000, 90.000, size=1500)

array([ 86.96586206, -70.99243448,  36.76840028, ..., -36.61846715,
        73.85927917, -35.75687434])